
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `psych`=list(
        `type`="software", 
        `author`="Revelle, W.", 
        `year`=2019, 
        `title`="psych: Procedures for Psychological, Psychometric, and Personality Research", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=psych", 
        `url`="https://CRAN.R-project.org/package=psych"), 
    `recist`=list(
        `type`="article", 
        `author`="Eisenhauer EA, Therasse P, Bogaerts J, Schwartz LH, Sargent D, Ford R, Dancey J, Arbuck S, Gwyther S, Mooney M, Rubinstein L, Shankar L, Dodd L, Kaplan R, Lacombe D, Verweij J.", 
        `year`=2009, 
        `title`="New response evaluation criteria in solid tumours: revised RECIST guideline (version 1.1).", 
        `publisher`="Eur J Cancer.", 
        `volume`="45(2)", 
        `pages`="228-47", 
        `doi`="10.1016/j.ejca.2008.10.026", 
        `url`="https://pubmed.ncbi.nlm.nih.gov/19097774/"), 
    `ClinicoPathJamoviModule`=list(
        `type`="software", 
        `author`="Serdar Balci", 
        `year`=2022, 
        `title`="ClinicoPath jamovi Module doi:10.5281/zenodo.3997188", 
        `publisher`="[R package]. Retrieved from https://github.com/sbalci/ClinicoPathJamoviModule", 
        `doi`="10.17605/OSF.IO/9SZUD", 
        `url`="https://www.serdarbalci.com/ClinicoPathJamoviModule/"), 
    `ggswim`=list(
        `type`="software", 
        `author`="Richard Hanna, Stephan Kadauke, Ezra Porter", 
        `year`=2025, 
        `title`="ggswim: Create Swimmer Plots with ggplot2", 
        `publisher`="[R package]. Retrieved from https://github.com/CHOP-CGTInformatics/ggswim", 
        `url`="https://github.com/CHOP-CGTInformatics/ggswim"), 
    `metafor`=list(
        `type`="software", 
        `author`="Wolfgang Viechtbauer", 
        `year`=2026, 
        `title`="metafor: R package", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=metafor", 
        `url`="https://CRAN.R-project.org/package=metafor"), 
    `mada`=list(
        `type`="software", 
        `author`="Philipp Doebler", 
        `year`=2025, 
        `title`="mada: R package", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=mada", 
        `url`="https://CRAN.R-project.org/package=mada"))
