# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'diagnosticmeta_test_categorical' so R CMD check does not flag undocumented data.
#' diagnosticmeta_test_categorical: example dataset for the OncoPath module
#'
#' Example dataset distributed with the OncoPath jamovi module for demonstration and testing.
#'
#' @format A data frame with 20 rows and 8 variables:
#' \describe{
#'   \item{study}{character variable}
#'   \item{true_positives}{numeric variable}
#'   \item{false_positives}{numeric variable}
#'   \item{false_negatives}{numeric variable}
#'   \item{true_negatives}{numeric variable}
#'   \item{year}{integer variable}
#'   \item{quality_score}{numeric variable}
#'   \item{imaging_modality}{character variable}
#' }
#' @keywords datasets internal
"diagnosticmeta_test_categorical"

