# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'ihcheterogeneity_test' so R CMD check does not flag undocumented data.
#' ihcheterogeneity_test: example dataset for the OncoPath module
#'
#' Example dataset distributed with the OncoPath jamovi module for demonstration and testing.
#'
#' @format A data frame with 50 rows and 7 variables:
#' \describe{
#'   \item{case_id}{character variable}
#'   \item{wholesection}{numeric variable}
#'   \item{biopsy1}{numeric variable}
#'   \item{biopsy2}{numeric variable}
#'   \item{biopsy3}{numeric variable}
#'   \item{biopsy4}{numeric variable}
#'   \item{spatial_id}{character variable}
#' }
#' @keywords datasets internal
"ihcheterogeneity_test"

