# Generated by _updateModules.R from explicitly selected umbrella helpers.
# Edit the source named in _updateModules_config.yaml, not this file.

.quietly <- function(expr, deprecation_pattern = paste("deprecat", "defunct", "superseded", "will change from", 
    "is no longer", "renamed", "future version", "startup", sep = "|")) {
    withCallingHandlers(suppressMessages(suppressPackageStartupMessages(expr)), warning = function(w) {
        if (grepl(deprecation_pattern, conditionMessage(w), ignore.case = TRUE)) 
            invokeRestart("muffleWarning")
    })
}

.fmt <- function(.format_string, ...) {
    values <- list(...)
    risky <- vapply(values, function(v) {
        v <- tryCatch(as.character(v), error = function(e) "")
        length(v) > 0L && any(grepl("{", v, fixed = TRUE), na.rm = TRUE)
    }, logical(1))
    if (any(risky)) {
        values[risky] <- lapply(values[risky], function(v) {
            v <- as.character(v)
            v <- gsub("{", "(", v, fixed = TRUE)
            gsub("}", ")", v, fixed = TRUE)
        })
        return(do.call(jmvcore::format, c(list(.format_string), values)))
    }
    do.call(jmvcore::format, c(list(.format_string), values))
}

`%||%` <- function(x, y) if (is.null(x)) y else x

